# Generated by Django 5.1.1 on 2025-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('tugallangan', 'Tugallangan'), ('tugallanmagan', 'Tugallanmagan')], default='tugallanmagan', max_length=50)),
            ],
        ),
    ]
